######################################################################
# Automatically generated by qmake (2.01a) vie mar 6 16:08:49 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += clientcore.h lilchat.h servercore.h
FORMS += lilchat.ui
SOURCES += clientcore.cpp lilchat.cpp main.cpp servercore.cpp
QT += network
