#############################################################################
# Makefile for building: lilChat
# Generated by qmake (2.01a) (Qt 4.4.3) on: vie mar 6 16:09:04 2009
# Project:  lilChat.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile lilChat.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=i686 -mtune=generic -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=i686 -mtune=generic -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/QtGui -I/usr/include -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/lib
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -L/usr/lib -L/usr/X11R6/lib -pthread -lpng -lSM -lICE -pthread -pthread -lXi -lXrender -lXrandr -lXfixes -lXcursor -lXinerama -lfreetype -lfontconfig -lXext -lX11 -lQtNetwork -lssl -lcrypto -pthread -pthread -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = clientcore.cpp \
		lilchat.cpp \
		main.cpp \
		servercore.cpp moc_clientcore.cpp \
		moc_lilchat.cpp \
		moc_servercore.cpp
OBJECTS       = clientcore.o \
		lilchat.o \
		main.o \
		servercore.o \
		moc_clientcore.o \
		moc_lilchat.o \
		moc_servercore.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		lilChat.pro
QMAKE_TARGET  = lilChat
DESTDIR       = 
TARGET        = lilChat

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_lilchat.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: lilChat.pro  /usr/share/qt/mkspecs/linux-g++/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl \
		/usr/lib/libQtNetwork.prl
	$(QMAKE) -unix -o Makefile lilChat.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
/usr/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile lilChat.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/lilChat1.0.0 || $(MKDIR) .tmp/lilChat1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/lilChat1.0.0/ && $(COPY_FILE) --parents clientcore.h lilchat.h servercore.h .tmp/lilChat1.0.0/ && $(COPY_FILE) --parents clientcore.cpp lilchat.cpp main.cpp servercore.cpp .tmp/lilChat1.0.0/ && $(COPY_FILE) --parents lilchat.ui .tmp/lilChat1.0.0/ && (cd `dirname .tmp/lilChat1.0.0` && $(TAR) lilChat1.0.0.tar lilChat1.0.0 && $(COMPRESS) lilChat1.0.0.tar) && $(MOVE) `dirname .tmp/lilChat1.0.0`/lilChat1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/lilChat1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_clientcore.cpp moc_lilchat.cpp moc_servercore.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_clientcore.cpp moc_lilchat.cpp moc_servercore.cpp
moc_clientcore.cpp: clientcore.h
	/usr/bin/moc $(DEFINES) $(INCPATH) clientcore.h -o moc_clientcore.cpp

moc_lilchat.cpp: lilchat.h
	/usr/bin/moc $(DEFINES) $(INCPATH) lilchat.h -o moc_lilchat.cpp

moc_servercore.cpp: servercore.h
	/usr/bin/moc $(DEFINES) $(INCPATH) servercore.h -o moc_servercore.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_lilchat.h
compiler_uic_clean:
	-$(DEL_FILE) ui_lilchat.h
ui_lilchat.h: lilchat.ui
	/usr/bin/uic lilchat.ui -o ui_lilchat.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

clientcore.o: clientcore.cpp clientcore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientcore.o clientcore.cpp

lilchat.o: lilchat.cpp lilchat.h \
		ui_lilchat.h \
		clientcore.h \
		servercore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lilchat.o lilchat.cpp

main.o: main.cpp lilchat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

servercore.o: servercore.cpp servercore.h \
		lilchat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o servercore.o servercore.cpp

moc_clientcore.o: moc_clientcore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clientcore.o moc_clientcore.cpp

moc_lilchat.o: moc_lilchat.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lilchat.o moc_lilchat.cpp

moc_servercore.o: moc_servercore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_servercore.o moc_servercore.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

